version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - arm64
      - amd64

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

dockers_v2:
  - dockerfile: "./build/Dockerfile"
    images: 
      - "ghcr.io/suyash-811/cert-watch-operator"
    tags:
      - "v{{ .Version }}"
      - "v{{ .Major }}"
      - "v{{ .Major }}.{{ .Minor }}"
      - "latest"
    annotations:
      "org.opencontainers.image.description": "Kubernetes controller to watch certificates and print their expiry"
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "https://github.com/suyash-811/cert-watch-operator"
      "org.opencontainers.image.url": "https://github.com/suyash-811/cert-watch-operator"

    platforms:
      - linux/amd64
      - linux/arm64

changelog:
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
