apiVersion: monitoring.sonaw.net/v1alpha1
kind: CertificateWatcher
metadata:
  labels:
    app.kubernetes.io/name: cert-watch-operator
    app.kubernetes.io/managed-by: kustomize
  name: certificatewatcher-sample
spec:
  secretName: foo
  secretKey: bar
